-- Active: 1731384027892@@127.0.0.1@3306@aloha
-- Active: 1731904938494@@127.0.0.1@3306@ckauto
DROP TABLE IF EXISTS `files`;

CREATE TABLE `files` (
	`no`	BIGINT	NOT NULL AUTO_INCREMENT PRIMARY KEY	COMMENT 'PK',
	`id`	VARCHAR(64)	NOT NULL	COMMENT 'UK',
	`p_table`	VARCHAR(100)	NOT NULL	COMMENT '부모테이블',
	`p_no`	BIGINT	NOT NULL	COMMENT '부모PK',
	`type`	ENUM('MAIN', 'SUB')	NOT NULL	DEFAULT 'SUB'	COMMENT '타입',
	`file_name`	TEXT	NOT NULL	COMMENT '파일명',
	`origin_name`	TEXT	NOT NULL	COMMENT '원본파일명',
	`file_path`	TEXT	NOT NULL	COMMENT '파일경로',
	`file_size`	BIGINT	NULL	DEFAULT 0	COMMENT '용량',
	`seq`	BIGINT	NULL	DEFAULT 0	COMMENT '순서',
	`created_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '등록일자',
	`updated_at`	TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP	COMMENT '수정일자'
) COMMENT '파일';